#!/bin/bash

autorandr -c

killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar --reload main &
done

xset -dpms
xset s off
