#! /bin/sh

picom &
numlockx &
nm-applet &
blueman-applet &
pasystray &
redshift-gtk &
gxkb &
alttab -d 1 -w 1 -bg "#50514f" -fg "#b4adea" -frame "#b4adea" &

setxkbmap -layout "us,cz(qwerty)" -option grp:shifts_toggle

disable_touchpad

