#! /bin/sh


#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP -d I II III IV
bspc monitor HDMI-A-0 -d V VI VII VIII XI

bspc config border_width        3
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on

disable_touchpad
init_monitors
